sudo: true
dist: xenial
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
matrix:
  fast_finish: true
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: pmclanahan
  skip_cleanup: true
  skip_upload_docs: true
  on:
    tags: true
    repo: mozilla/basket-client
    python: '3.6'
  password:
    secure: V60MXU5mizCNkz3JXv1ICw3usjk5ftqfBi+HgOIHPf8TyRNUGUeWIwwrkB3SrYqu06rylpSsskMbxUINYTQvpYyDI9ZaPyCQ0D8mdGapJ3v3ba+owTxHhbnrtOazqOC1Ypux2yXEfsw8VFqPT6gAq1RtFeecA1E+8/oLJE9mq4Q=
