[tool.black]
line-length = 150
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.tox
  | \.venv
  | _build
  | build
  | dist
  | docs
)/
'''

[tool.ruff]
# Set what ruff should check for.
# See https://beta.ruff.rs/docs/rules/ for a list of rules.
select = [
    "A", # flake8-builtin errors.
    # "B", # bugbear errors
    "E", # pycodestyle errors
    "F", # pyflakes errors
    "I", # import sorting
    "Q", # flake8-quotes errors
    "W", # pycodestyle warnings
]
line-length = 150  # To match black.
target-version = 'py39'
extend-exclude = ["docs"]

[tool.ruff.isort]
known-first-party = ["basket"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37,py38,py39,py310,py37-lint

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310

[testenv]
deps = -rrequirements/dev.txt
commands =
    pytest basket/tests.py

[testenv:py37-lint]
basepython = python3.7
changedir = {toxinidir}
commands = 
    black --check basket setup.py
    ruff basket setup.py
"""